@ECHO OFF
ECHO Profiling %1 ...
python -m cProfile -o %1.pstats %*
ECHO Generating image ...
python gprof2dot.py -f pstats %1.pstats | "c:\Program Files (x86)\Graphviz2.32\bin\dot" -Gcharset=latin1 -Tpng -o %1.png
ECHO Displaying image ...
%1.png