Document: dsr
Title: Debian dsr Manual
Author: <insert document author here>
Abstract: This manual describes what dsr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dsr/dsr.sgml.gz

Format: postscript
Files: /usr/share/doc/dsr/dsr.ps.gz

Format: text
Files: /usr/share/doc/dsr/dsr.text.gz

Format: HTML
Index: /usr/share/doc/dsr/html/index.html
Files: /usr/share/doc/dsr/html/*.html
