name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    #env:
      #DSR_DIR: $(${HOME})/.local/bin

    steps:
      - name: Install xclip
        run: sudo apt-get install -y xclip
      - uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Test with Unittest
        run: |
          export DSR_DIR=${HOME}/.local/bin
          mkdir -p ${HOME}/.local/bin
          echo ${HOME}/.local/bin >> $GITHUB_PATH
          echo ${HOME}/.local/bin mypath
          chmod a+x setup/dsr.sh
          cp -r setup/dsr.sh ${HOME}/.local/bin/dsr
          cp -r * ${HOME}/.local/bin/
          
          cd tests
          pytest
          # PYTHONPATH=../$pwd python2 test_all.py
          # PYTHONPATH=../$pwd python2 ffit_tests/test_fastfit.py