name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DSR_DIR: /opt/DSR

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Test with Unittest
        run: |
          #echo "$(pwd)" >> $PATH
          mkdir -p "${HOME}/.local/bin"
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
          echo "${HOME}/.local/bin" mypath
          chmod a+x dsr
          cp -r * "${HOME}/.local/bin/"
          dsr -l
          
          cd tests
          pytest
          # PYTHONPATH=../$pwd python2 test_all.py
          # PYTHONPATH=../$pwd python2 ffit_tests/test_fastfit.py