name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install xclip
        run: sudo apt-get install -y xclip
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Test with Pytest
        run: |
          export DSR_DIR=${HOME}/.local/bin
          mkdir -p ${HOME}/.local/bin
          echo ${HOME}/.local/bin >> $GITHUB_PATH
          curl -o ${HOME}/.local/bin/shelxl https://dkratzert.de/files/shelx/shelxl
          chmod a+x setup/dsr.sh
          chmod a+x ${HOME}/.local/bin/shelxl
          cp -r setup/dsr.sh ${HOME}/.local/bin/dsr
          cp -r * ${HOME}/.local/bin/
          
          export PYTHONPATH=src/dsr
          export DSR_DIR=src/dsr
          pytest --verbose