name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        os: [ ubuntu-latest ]

    steps:
      - name: Install xclip
        run: sudo apt-get install -y xclip
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Test with Pytest
        run: |
          export DSR_DIR=${HOME}/.local/bin
          mkdir -p ${HOME}/.local/bin
          echo ${HOME}/.local/bin >> $GITHUB_PATH
          curl -o ${HOME}/.local/bin/shelxl https://dkratzert.de/files/shelx/shelxl
          chmod a+x src/dsr_shelx/dsr
          chmod a+x ${HOME}/.local/bin/shelxl
          cp -r src/dsr_shelx/dsr ${HOME}/.local/bin/dsr
          cp -r * ${HOME}/.local/bin/
          
          export DSR_DIR=src/dsr_shelx
          pytest --verbose